apiVersion: v1
kind: Namespace
metadata:
  name: website

---

kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: website-mysql
  name: website-mysql
  namespace: website
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    k8s-app: website-mysql

---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: website-mysql-pv-volume
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: website-mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    k8s-app: website-mysql
  name: website-mysql
  namespace: website
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: website-mysql
  template:
    metadata:
      labels:
        k8s-app: website-mysql
    spec:
      containers:
        - name: website-mysql
          image: mysql:latest
          env:
            - name: MYSQL_DATABASE
              value: ghost
            - name: MYSQL_USER
              value: ghost_user
            - name: MYSQL_PASSWORD
              value: Mh2URVnwF5caZatb
            - name: MYSQL_ROOT_PASSWORD
              value: E73ycu9TQaZufcsB
